apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-node-app
  namespace: bermtec
  labels:
    app: docker-node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker-node
  template:
    metadata:
      labels:
        app: docker-node
    spec:
      containers:
      - name: docker-node-app
        image: acrkcr.azurecr.io/img:1.0
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: new-secret
