apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-node
  labels:
    app: docker-node
spec:
  replicas: 3
  selector:
    matchLabels: test
      app: docker-node
  template:
    metadata:
      labels: test
        app: nginx
    spec:
      containers:
      - name: docker-node
        image: docker-node-app:latest
        ports:
        - containerPort: 80